
baseurl: ""
production_url : http://greystate.github.io.com/
BASE_PATH : http://greystate.dk/

permalink: /:categories/:year/:month/:day/:title/

source: .
destination: _site

exclude: [CNAME, src, config.codekit3]

highlighter: none

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      author: Chriztian Steinmeier

plugins:
  - jekyll-feed
